language: python
# if command bellow need to executed in sudo
# add this line.
# sudo: required
python:
  - 3.5
  - 3.6
services:
  - mongodb
install:
  - pip install -r requirements.txt
script:
  - bash run.sh
  - cd calApi; python manage.py test;