# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170813_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='', max_length=3),
        ),
    ]
